# Generated by Django 3.2.13 on 2022-06-01 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('schedule_id', models.CharField(max_length=100)),
                ('appointment_date', models.CharField(max_length=70)),
                ('month', models.CharField(max_length=70)),
                ('preacher_id', models.CharField(max_length=70)),
                ('topic_id', models.CharField(max_length=70)),
                ('location_id', models.CharField(max_length=70)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Precher',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('availability_dates', models.JSONField(blank=True)),
                ('contact_info', models.CharField(max_length=70)),
                ('type', models.JSONField(blank=True)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=70)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
