# Generated by Django 3.2.13 on 2022-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.JSONField(blank=True),
        ),
    ]
