# Generated by Django 3.2.13 on 2022-06-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_topic_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precher',
            new_name='Preacher',
        ),
    ]
